name: Deploy Backend to NCP

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    paths:
      - "server/**"
      - ".github/workflows/deploy-backend.yml"
      - "deploy/**"

jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy .env file
        working-directory: ./deploy
        run: |
          cp ~/deploy/.env ./.env

          if [ ! -f .env ]; then
            echo ".env file not exists"
            exit 1
          fi 

          echo ".env file copied."

      - name: Blue-Green Release (Compose + Nginx Switch)
        working-directory: ./deploy
        run: |
          chmod +x ./deploy.sh 
          ./deploy.sh

      - name: Show container logs
        working-directory: ./deploy
        if: always()
        run: |
          docker compose -f compose.blue-green.yml logs --tail=50

      - name: Clean
        if: always()
        working-directory: ./deploy
        run: |
          docker image prune -f --filter "until=336h"     # 14일
          docker builder prune -f --filter "until=336h"   
          docker container prune -f --filter "until=168h" # 7일
          docker network prune -f --filter "until=168h"
